apiVersion: v1
kind: Secret
metadata:
  name: {{ include "xwrag.fullname" . }}-env
  labels:
    {{- include "xwrag.labels" . | nindent 4 }}
type: Opaque
stringData:
  .env: |-
    {{- include "xwrag.envContent" . | nindent 4 }}
